##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  pig配置  ###################
pig:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  项目启动端口  ###################
server:
  port: 8082


###################  MyBatis 配置  ###################
mybatis:
  type-aliases-package: com.one.pig
  mapper-locations: classpath:mapper/*.xml


###################  MyBatis 分页插件配置  ###################
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false

###################  spring配置  ###################
spring:
  redis:
    host: 47.98.107.248
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 0ms
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
      suffix: .jsp
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
#      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  output:
    ansi:
      enabled: always
  resources:
    static-locations: ["classpath:/MATE-INF","classpath:/WEB-INFO/view"]
mapper:
  mappers: com.one.pig
  not-empty: false
  identity: MYSQL
##配置日志
#logging:
#  #配置日志文件路径
#  level:
#    xatu.zsl: debug #不同目录下的日志可配置不同级别
#    org.springfromework.web: info
#    org.hibernate: error
#  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
#  file: log\myspringboot.log
#  pattern:
#    dateformat: yyyy-MM-dd HH:mm:ss.SSS
---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://47.98.107.248:3306/one_pig?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: csy458721
    filters: log4j,wall,mergeStat

#多数据源
biz:
  datasource:
    url: jdbc:mysql://47.98.107.248:3306/biz?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: csy458721

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: pig.log

---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://47.98.107.248:3306/one_pig?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: csy458721
    filters: log4j,wall,mergeStat

logging:
  level.root: warn
  path: logs/
  file: pig.log

